[project]
name = "aline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.2.1",
    "pandas>=2.2.3",
    "scipy>=1.15.0",
    "openpyxl>=3.1.5",
    "matplotlib>=3.10.0",
    "seaborn>=0.13.2",
]
